### ISSUE TITLE
Ptt not working in lumicall

### ISSUE THREAD

**Issue by sshh** [opentelecoms-org/lumicall#18]
I installed the application lumicall in my mobile, and i need to communicate via ptt. There is a button named Send/ptt in the app but when we press the button nothing is happening.. I need to communicate with others through wifi network but the ptt button is not working. How to make the ptt work in the lumicall application?

**Comment by dpocock** [comment]
PTT is an experimental feature and it is not a complete implementation.

I've disabled it by default in the latest versions of Lumicall, you can re-enable it through the settings.   It needs more development work before it is complete.

It currently only uses multicast so it won't work across routers that block multicast.  Multicast over wifi can also drain the battery more quickly.
