### ISSUE TITLE
sip5060 reg

### ISSUE THREAD

**Issue by xeverse** [opentelecoms-org/lumicall#19]
Hello, how can i reg a user on sip560
if i never use any sim card with my android at all, 
because of privacy concerns?

Why there's no open registration anyway?

By the way, this project looks very interesting.
I'm having some issues with sip on my platform with ostn though 
and i have even been thinking of switching to xmpp/jingle completely.

**Comment by dpocock** [comment]
You can create a SIP account with any SIP provider and then use the manual registration in Lumicall.

I've also made it easier to add an account, please look in the preferences, the Add button is more obvious.
